services:
  - type: web
    name: collectam
    repo: https://github.com/lionel299/collectam
    branch: main
    runtime: node
    buildCommand: npm install
    startCommand: npm run server
    envVars:
      - key: MONGODB_URI
        sync: false

  - type: static_site
    name: post
    repo: https://github.com/lionel299/post
    branch: main
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VUE_APP_API_URL
        value: https://backend.onrender.com

